<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Session;
use think\Request;
class Common extends Controller {

    protected  $request;

    public function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       $this->request;
   }


}
