<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Session;
use think\Request;
class Common extends Controller {

    protected  $request;

    protected  $session = '';

    protected $beforeActionList = [
        'check'
    ];

    public function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       $this->request;
       $this->session = new Session();
   }


    protected function check()
    {
        if(!$this->session->get('member')){
           return  $this->redirect('login/login');
        }
    }

}
